//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preparation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.productsale = new HashSet<productsale>();
        }
    
        public int ИН_Агента { get; set; }
        public string Тип { get; set; }
        public string Наименование { get; set; }
        public string Почта { get; set; }
        public string Телефон { get; set; }
        public string Логотип { get; set; }
        public string Юр__адрес { get; set; }
        public Nullable<int> Приоритет { get; set; }
        public string Директор { get; set; }
        public string ИНН { get; set; }
        public string КПП { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productsale> productsale { get; set; }
    }
}
