//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preparation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class poprizhenokEntities : DbContext
    {
        private static poprizhenokEntities _context;

        public static poprizhenokEntities GetContext()
        {
            if (_context == null)

                _context = new poprizhenokEntities();
            return _context;
        }

        public poprizhenokEntities()
            : base("name=poprizhenokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<productsale> productsale { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
