//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preparation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rusmetEntities1 : DbContext
    {
        private static rusmetEntities1 _context;

        public static rusmetEntities1 GetContext()
        {
            if (_context == null)

                _context = new rusmetEntities1();
            return _context;
        }
        public rusmetEntities1()
            : base("name=rusmetEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Деталь> Деталь { get; set; }
        public virtual DbSet<Журнал_изменений> Журнал_изменений { get; set; }
        public virtual DbSet<Категория> Категория { get; set; }
        public virtual DbSet<Фотография> Фотография { get; set; }
        public virtual DbSet<Характеристика_детали> Характеристика_детали { get; set; }
        public virtual DbSet<Характеристики> Характеристики { get; set; }
    }
}
