//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preparation
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsale
    {
        public int ИН_Продажи { get; set; }
        public string Продукция { get; set; }
        public Nullable<int> ИН_Агента { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Кол_во { get; set; }
    
        public virtual Agents Agents { get; set; }
    }
}
