//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preparation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Деталь
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Деталь()
        {
            this.Фотография = new HashSet<Фотография>();
            this.Характеристика_детали = new HashSet<Характеристика_детали>();
        }
    
        public int Id_детали { get; set; }
        public Nullable<int> Id_категории { get; set; }
        public string Название { get; set; }
        public string Модель { get; set; }
        public string ГОСТ { get; set; }
        public string Номер_чертежа { get; set; }
        public string Описание { get; set; }
        public bool Видимость { get; set; }
    
        public virtual Категория Категория { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Фотография> Фотография { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Характеристика_детали> Характеристика_детали { get; set; }
    }
}
