//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preparation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Характеристика_детали
    {
        public int Id { get; set; }
        public int Id_детали { get; set; }
        public int Id_характеристики { get; set; }
        public Nullable<double> Значение { get; set; }
        public string Ед__измерения { get; set; }
    
        public virtual Деталь Деталь { get; set; }
        public virtual Характеристики Характеристики { get; set; }
    }
}
